org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=1.19.2
minecraft_version_range=[1.19.2, 1.19.3)
forge_version=43.2.14
forge_version_range=[43,)
loader_version_range=[43,)
mapping_channel=parchment
mapping_version=2022.08.14-1.19.2
mod_id=nffgirlsgaia
archive_base_name=nffgirls-gaia-1.19.2
mod_name=NFF: Girls - Grimoire of Gaia Addon
mod_license=LGPL-3.0
mod_group_id=net.sodiumzh.nff.girls.gaia
mod_authors=SodiumZH
mod_description=NFF Girls support of Grimore of Gaia. More girls to be friends!
jei_version=11.6.0.1015
mixinextras_version=0.3.1
mixinextras_version_range=[0.3.0,)

mod_version=0.1.30
filename_version=0.1.30-dev-250525
girls_version=0.1.30
girls_version_range=[0.1.30, 0.1.31)
girls_version_filename=0.1.30-dev-250524
services_version=0.1.30-dev
services_version_range=[0.1.30, 0.1.31)
nautils_version=0.1.30
gaia_version_range=[3.0.0-alpha.14, 4)
